name: CI

on:
  push:
    branches:
      - "main"
    tags:
      - "v*"
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_NAME: fabienmarty/gatus-cloudrun

jobs:
  main_ci:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # we need this because fetch-tags=true and because of a GHA bug: https://github.com/actions/checkout/issues/1471
          fetch-tags: true
          ref: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.ref }} # because actions/checkout@v4 adds a kind of merge commit in some cases
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
      - name: Compute version
        id: version
        run: |
          export VERSION=`uv run --script --no-project version.py`
          echo "### Version: ${VERSION} ðŸš€" >>${GITHUB_STEP_SUMMARY}
          echo "version=${VERSION}" >>${GITHUB_OUTPUT}
          echo "VERSION=${VERSION}"
          echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}" >>${GITHUB_OUTPUT}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Login to Docker Hub Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: docker
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.version.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
