name: CI

on:
    push:
        branches:
            - "main"
    pull_request:

env:
    REGISTRY: docker.io
    IMAGE_NAME: fabienmarty/gatus-cloudrun

jobs:
    main_ci:
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v5
              with:
                  fetch-depth: 0 # we need this because fetch-tags=true and because of a GHA bug: https://github.com/actions/checkout/issues/1471
                  fetch-tags: true
            - name: Set up uv
              uses: astral-sh/setup-uv@v6
              with:
                  python-version: 3.12
            - name: Compute version
              id: version
              run: |
                  export VERSION=`uv run --script --no-project version.py`
                  echo "### Version: ${VERSION} ðŸš€" >>${GITHUB_STEP_SUMMARY}
                  echo "version=${VERSION}" >>${GITHUB_OUTPUT}
                  echo "VERSION=${VERSION}"
                  if test "${{ github.event_name }}/${{ github.ref }}" = "push/refs/heads/main"; then
                    echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest" >>${GITHUB_OUTPUT}
                  else
                    echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${VERSION}" >>${GITHUB_OUTPUT}
                  fi
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Login to Docker Hub Registry
              if: ${{ github.event_name == 'push' }}
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_HUB_LOGIN }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            - name: Build and push image
              uses: docker/build-push-action@v5
              with:
                  context: docker
                  push: ${{ github.event_name == 'push' }}
                  tags: ${{ steps.version.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
